"""change to string

Revision ID: 61be98e3d7a9
Revises: 7fbf89ffe20c
Create Date: 2024-06-27 22:20:35.677240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61be98e3d7a9'
down_revision = '7fbf89ffe20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
