"""change email to mail

Revision ID: c34062ecfd97
Revises: f9ab4822ee3e
Create Date: 2024-06-28 02:12:10.695984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34062ecfd97'
down_revision = 'f9ab4822ee3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail', sa.String(), nullable=True))
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('mail')

    # ### end Alembic commands ###
